version: "3.8"

services:
    app:
        image: online_store:1.0.0
        container_name: online_store
        build: .
        restart: on-failure
        ports:
            - "8000:8000"
        # expose:
        #   - 8000
        volumes:
            - .:/usr/src/app/
        env_file:
            - ${ENVFILE:-.env}
        depends_on:
            - postgres
            - redis

    postgres:
        image: postgres:14.5-alpine
        ports:
          - 5432:5432
        environment:
            POSTGRES_PORT: 5432
            POSTGRES_DB: "online_store"
            POSTGRES_USER: "online_store"
            POSTGRES_PASSWORD: "online_store"
        volumes:
            - postgres-data:/var/lib/postgresql/data/

    redis:
        image: redis:6.2.7-alpine
        ports:
            - 6379:6379 
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - redis-data:/data

volumes:
    postgres-data:
    redis-data:
