# Generated by Django 4.1.6 on 2023-02-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordermanagement', '0002_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['user'], 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
    ]
